### ISSUE TITLE
Question not using Google Play Services?

### ISSUE THREAD

**Issue by LudovicBouvierJohnston** [mertcansegmen/LocationBasedReminder#1]
Awesome app I was looking for something similar for the Android version. I am coming from an iPhone with Apple Reminders and in it seems in Android that feature is missing. I was wondering why you didn't use the Geofencing feature in Google Play Services. It seems Google Play Services would handle this more efficiently? Here is the docs.   https://developer.android.com/training/location/geofencing

Hope i get answer soon. Take care ! 😃

**Comment by mertcansegmen** [comment]
Hi @LudovicBouvierJohnston, I made this app as my college capstone project and when I realized that the app was using more battery than it should've been, my project was already graded. After some research, I found the geofencing documentation, but I was just too lazy to implement it, so that's the reason 😃.

It's been a long time since I worked on Android development, and I don't plan to continue developing the app.

Sorry for the late reply, take care 🙂
